CREATE TABLE animals (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL(10, 2) 
);

-- Add a column species of type string to your animals table. 
ALTER TABLE animals ADD COLUMN species VARCHAR(100);


/* OWNERS TABLE*/
CREATE TABLE IF NOT EXISTS owners (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(100),
    age INT
);

select *from owners;
/*SPECIES TABLE */
CREATE TABLE IF NOT EXISTS species (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50)
);

/*MODIFY ANIMALS TABLE*/
/* Make id auto-increment (PostgreSQL uses SERIAL/IDENTITY) */
ALTER TABLE animals
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

/* Remove old species column (string) */
ALTER TABLE animals
DROP COLUMN IF EXISTS species;

/* Add foreign keys */
ALTER TABLE animals
ADD COLUMN species_id INT,
ADD COLUMN owner_id INT;

/* Add constraints */
ALTER TABLE animals
ADD CONSTRAINT fk_species
FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals
ADD CONSTRAINT fk_owner
FOREIGN KEY (owner_id) REFERENCES owners(id);
